name: .NET Core

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: |
        cd src/
        dotnet restore
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build package for Release
      run: |
        cd src/
        echo $GITHUB_RUN_NUMBER
        dotnet pack -c Release
    - name: Push package to nuget
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: dotnet nuget push **/SmartHead.EfCore.Extensions.*.nupkg -k $NUGET_KEY -s https://www.nuget.org/api/v2/package --skip-duplicate
